---
name: Workflow for Codecov wrapper
on:  # yamllint disable-line rule:truthy
  - push
  - pull_request
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install -r app/requirements.txt
      - name: Run tests and collect coverage
        run: pytest --cov app ${{ env.CODECOV_ATS_TESTS }}
      - name: Upload coverage to Codecov
        run: ./dist/codecov.sh
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
          CODECOV_FAIL_ON_ERROR: true
          CODECOV_FLAGS: flag1,flag2
  shellcheck:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install shellcheck
        run: brew install shellcheck
      - name: Run shellcheck
        # TODO: fix shellcheck
        # run: shellcheck dist/codecov.sh -x
        run: shellcheck dist/codecov.sh
