---
name: Push new tagged version
on:  # yamllint disable-line rule:truthy
  workflow_dispatch:
  push:
    # Pattern matched against refs/tags
    tags:
      - '*'

jobs:
  set-version:
    runs-on: ubuntu-latest
    steps:
      - name: Set version variable
        run: |
          version=$(cat scripts/version.sh | grep 'CODECOV_WRAPPER_VERSION=' | cut -d\" -f2)
          echo "CODECOV_WRAPPER_VERSION=$version" >> $GITHUB_ENV

  bitrise-step:
    needs: set-version
    uses: ././github/workflows/push-tag.yml
    with:
      repository: "codecov/codecov-bitrise"
      version: ${{ env.CODECOV_WRAPPER_VERSION }}
